spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true

resilience4j.ratelimiter.instances.login.limit-for-period=5
resilience4j.ratelimiter.instances.login.limit-refresh-period=1m
resilience4j.ratelimiter.instances.login.timeout-duration=0s

resilience4j.ratelimiter.instances.register.limit-for-period=3
resilience4j.ratelimiter.instances.register.limit-refresh-period=1m
resilience4j.ratelimiter.instances.register.timeout-duration=0s

resilience4j.ratelimiter.instances.apiproducts.limit-for-period=30
resilience4j.ratelimiter.instances.apiproducts.limit-refresh-period=1m
resilience4j.ratelimiter.instances.apiproducts.timeout-duration=0s

resilience4j.ratelimiter.instances.apicarrinho.limit-for-period=30
resilience4j.ratelimiter.instances.apicarrinho.limit-refresh-period=1m
resilience4j.ratelimiter.instances.apicarrinho.timeout-duration=0s

resilience4j.ratelimiter.instances.apiusers.limit-for-period=20
resilience4j.ratelimiter.instances.apiusers.limit-refresh-period=1m
resilience4j.ratelimiter.instances.apiusers.timeout-duration=0s
api.security.token.secret=${JWT_SECRET}
server.address=0.0.0.0
server.port=${PORT:8080}